### ISSUE TITLE
Issue with signup

### ISSUE THREAD

**Issue by petrepatrasc** [auth0-samples/auth0-ionic2-samples#11]
Hey, we've been working on an Ionic 2 app for the last couple of months and we handle authentication across our web and backend using Auth0. Everything works fine, apart from the email sign-up workflow that has an annoying issue.

When the user signs up for a fresh account, their account is registered, their profile is retrieved and token storage works correctly, but they get an InAppBrowser tab with about:blank as the location. Once the user clicks on the done button to close the InAppBrowser, the workflow behaves as expected. 

I've found a very similar issue but unfortunately, it did not work for us: https://github.com/auth0/auth0-ionic/issues/17

I should mention that we're using:
* auth0-js: 7.6.1
* auth0-lock: 10.8.1
* Cordova CLI: 6.5.0
* Ionic Framework Version: 2.1.0
* Ionic CLI Version: 2.2.1
* Ionic App Lib Version: 2.2.0
* Ionic App Scripts Version: 0.0.45
* ios-deploy version: 1.9.0
* ios-sim version: 5.0.13
* OS: macOS Sierra
* Node Version: v6.7.0
* Xcode version: Xcode 8.2.1 Build version 8C1002

I should also mention that newer lock versions cause the sign-up flow to stop working altogether.

Have you encountered this before and do you know of any solutions?

**Comment by robzdc** [comment]
+1

**Comment by petrepatrasc** [comment]
@chenkie Hey, I also opened a support ticket about this within the dashboard but haven't had any responses. Can you please advise?

**Comment by nicosabena** [comment]
Fixed in [Lock v10.18](https://github.com/auth0/lock/releases/tag/v10.18.0).
