### ISSUE TITLE
Customize lock shown 

### ISSUE THREAD

**Issue by bschulzro** [auth0-samples/auth0-ionic2-samples#25]
Hello, 

How do you customize the lock shown after clicking on the login button ? 
I want to add some styles and properties to the lock. 

Thanks by you advance

**Comment by dhameer** [comment]
I second this request, want to have a custom logo as well. The https://auth0.com/docs/libraries/lock/v10/ui-customization doesn't help.

**Comment by bschulzro** [comment]
Hello @dhameer, i finally found how to customize the lock shown during login. The lock shown can be customized in the Hosted Pages section of Auth0. You can change and preview the login page there.

**Comment by dhameer** [comment]
yip thank you. just a side note. the changes made to hosted pages will affect all clients you may have.
