### ISSUE TITLE
Feature Request: Use Ionic Storage service

### ISSUE THREAD

**Issue by dankellett** [auth0-samples/auth0-ionic2-samples#32]
Ionic provides an abstraction to storage that uses the appropriate local storage that is available for that device.

https://ionicframework.com/docs/storage/

This example currently uses window.localStorage, but it seems that the better option would be to use the Ionic Storage service. Docs for this service located in the link above.

**Comment by ghost** [comment]
I think it's pretty easy to adapt Ionic Storage in the auth service on our own.

I've used Ionic Storage in a few projects and then switched back to the localStorage as it is more convenient to use for me.

**Comment by maxpaj** [comment]
I'm seeing that localStorage is wiped on iPhone models occasionally. I'm going to try using ionic storage instead and see if the effect persists.

**Comment by kmaida** [comment]
Please check out the updated Quick Start for Ionic 3, which uses Ionic storage: https://auth0.com/docs/quickstart/native/ionic3
