### ISSUE TITLE
Getting Error "Response state does not match expected state"

### ISSUE THREAD

**Issue by ankit-ilogix** [auth0-samples/auth0-ionic2-samples#43]
I have downoaded fresh demo from github repo. I using passwordless hosted page with ionic 3. I am getting below error after successfully login 

Error: "Response state does not match expected state." 

Please give your Help/suggestion for the same.

**Comment by ankit-ilogix** [comment]
@woloski  @tehsis  @lobo  @sandrinodimattia 
Can any one give answer on my issue?

**Comment by ankit-ilogix** [comment]
HOW POOR SUPPORT OF AUTH0. THIS WAS NOT EXPECTED FROM AUTH0.

@woloski @tehsis @lobo @sandrinodimattia

**Comment by aaguiarz** [comment]
Hi @ankit-ilogix,

This sample is designed to work with Ionic 2, we are working on a sample for Ionic 3. 

Regards,

Andres
